### PR TITLE
Import Bedtools intersect Nf-core

### PR DESCRIPTION
**Pull request by RojoCarrillo**
### Is there an existing PR for this?
- [X] I have searched for existing PRs

### Types of changes:
- [ ] Bug fix (change which fixes an identified problem)
- [X] "New" feature (change which adds or improves existing functionality)

### Description
Please include a summary of the changes and the related issue(s). List any dependencies that are required for this change, if any.

Fixes `#17`

### Checklist:
Please verify that you have completed the following:
- [X] Guidelines adherence: my changes follow the [guidelines](implementation_guidelines.md) of this project.
- [ ] Documentation update: I have made corresponding changes to the documentation, if necessary.
- [ ] Test inclusion: I have added tests that prove my code is effective and works.
- [ ] New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by yocra3** [comment]
Hola Juanjo,
Antes de aceptarte el PR, pon el issue que estas resolviendo.

**Comment by RojoCarrillo** [comment]
Issue #17 importar modulo bedtools intersect

**Comment by yocra3** [comment]
Ponmelo arriba del PR, por favor. Edita la plantilla.

**Comment by yocra3** [comment]
Perfecto. La acepto y mezcla. Cierra el issue cuando este aceptado el PR.
Buen trabajo!

**Review by yocra3 — APPROVED** [review]

**Pull request merged**
